services:
  api-gateway:
    build:
      context: ./backend
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    env_file: ./backend/.env

  users-service:
    build:
      context: ./backend
      dockerfile: services/users-service/Dockerfile
    env_file: ./backend/.env

  game-service:
    build:
      context: ./backend
      dockerfile: services/game-service/Dockerfile
    env_file: ./backend/.env

  matchmaker:
    build:
      context: ./backend
      dockerfile: services/matchmaker/Dockerfile
    env_file: ./backend/.env

  analysis-service:
    build:
      context: ./backend
      dockerfile: services/analysis-service/Dockerfile
    env_file: ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
#      args:
#        - VITE_API_URL=http://localhost:8000
    ports:
      - "8080:80"
    env_file: ./backend/.env
